#!/usr/bin/env python3
"""Lab 20-4 · The fence and the scorecard: the capstone's OpenShell policy, then every gate in one table.

Step 1 builds the capstone policy with Module 15's policykit: the sandbox may reach exactly two things,
inference.local (the brain, via `openshell inference set` → the gateway's `agent-brain` alias) and the
gateway on host.openshell.internal:4000 (the router tool). Not Spark B, not the internet.
Step 2 asks policykit's teaching model what that policy would allow for ten attempted actions,
during setup (pypi open) and after (pypi removed). policykit is course-made, not OpenShell.
Step 3 prints the OpenShell sequence (Module 15 lab 4, re-pointed at the gateway); it runs on the Spark
only with SPARK_APPLY=1 / --yes.
Step 4 is the capstone scorecard: the router's ship gate (Module 13), the agent scenarios (lab 20-3),
the policy checks (this lab). The course is done when every row is ✓ on real Sparks.

Run: .venv/bin/python week25/20_capstone_sovereign_agent/labs/lab04_sandbox_and_scorecard.py [--yes]
"""
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _capstone as C  # noqa: E402
from sparkkit import banner, check, note, put, result, sh, step, table, where  # noqa: E402

APPLY = os.environ.get("SPARK_APPLY") == "1" or "--yes" in sys.argv
SB = "hotel-capstone"
PK = C.PK
PY = ["/sandbox/.venv-nat/bin/python*", "/usr/bin/python3*"]

banner("Lab 20-4 · the fence and the scorecard", "least-privilege sandbox · every gate in one table")

step(1, "build and validate the capstone policy (Module 15's policykit)")
groups = {
    "inference": PK.group("inference", [{"host": "inference.local", "port": 443}], PY + ["/usr/bin/curl"]),
    "gateway": PK.group("gateway", [{"host": "host.openshell.internal", "port": 4000, "access": "full", "tls": "skip"}],
                        PY),                                   # plain HTTP to the gateway; without an access mode the proxy answers CONNECT 403
    "pypi": PK.group("pypi", [{"host": "pypi.org", "port": 443, "access": "full", "tls": "skip"},
                              {"host": "files.pythonhosted.org", "port": 443, "access": "full", "tls": "skip"}],
                     PY + ["/sandbox/.venv-nat/bin/pip*"]),
}
policy = PK.build_policy(read_only=["/usr", "/lib", "/proc", "/dev/urandom", "/etc"],
                         read_write=["/sandbox", "/tmp", "/dev/null"], groups=groups)
C.RUNS.mkdir(exist_ok=True)
pol_path = C.MOD / "policies" / "capstone_policy.yaml"
pol_path.write_text("# Week 25 · Capstone — generated by labs/lab04_sandbox_and_scorecard.py (policykit, Module 15).\n"
                    "# Course-designed, validated offline; not yet applied to a sandbox on a real Spark.\n"
                    + PK.dump(policy), encoding="utf-8")
errs, warns = PK.validate(policy)
check(not errs, f"policy valid · {len(groups)} network groups ({', '.join(groups)}) · {len(warns)} warning(s)",
      "; ".join(errs))
for w in warns:
    print(f"⚠ {w}")
note(f"written to {pol_path.relative_to(C.WEEK)}")

step(2, "what would it allow? (policykit's teaching model — not OpenShell)")
after = json.loads(json.dumps(policy))
after["network_policies"].pop("pypi")
ATTEMPTS = [
    ("router tool → gateway", {"op": "connect", "host": "host.openshell.internal", "port": 4000,
                               "binary": "/sandbox/.venv-nat/bin/python3.12"}, "allow"),
    ("brain → inference.local", {"op": "connect", "host": "inference.local", "port": 443,
                                 "binary": "/sandbox/.venv-nat/bin/python3.12"}, "*"),
    ("router tool → Spark B directly", {"op": "connect", "host": "spark-b", "port": 8000,
                                        "binary": "/sandbox/.venv-nat/bin/python3.12"}, "deny"),
    ("curl → gateway", {"op": "connect", "host": "host.openshell.internal", "port": 4000,
                        "binary": "/usr/bin/curl"}, "deny"),
    ("agent → api.openai.com", {"op": "connect", "host": "api.openai.com", "port": 443,
                                "binary": "/sandbox/.venv-nat/bin/python3.12"}, "deny"),
    ("write tickets.jsonl", {"op": "write", "path": "/sandbox/capstone/.runs/capstone_tickets.jsonl"}, "allow"),
    ("write /etc/hosts", {"op": "write", "path": "/etc/hosts"}, "deny"),
    ("read ~/.ssh on the host", {"op": "read", "path": "/home/nvidia/.ssh/id_ed25519"}, "deny"),
    ("run as root", {"op": "run_as", "user": "root"}, "deny"),
    ("pip install (after setup)", {"op": "connect", "host": "pypi.org", "port": 443,
                                   "binary": "/sandbox/.venv-nat/bin/pip"}, "deny"),
]
rows, fence_ok = [], True
for label_, action, want in ATTEMPTS:
    dec, why = PK.decide(after, action)
    ok = want == "*" or dec == want or (want == "allow" and dec == "inspect_for_inference")
    fence_ok &= ok
    rows.append([label_, dec, "✓" if ok else "✕", why[:58]])
table(rows, ["attempted action (after setup)", "decision", "", "why"])
check(fence_ok, "every attempt lands where the plan says: two ways out, nothing else",
      "an attempt was allowed that should be denied (or vice versa) — fix the policy before you push it")

step(3, "the OpenShell sequence on Spark A (Module 15 lab 4, re-pointed at the gateway)")


def change(cmd: str, example: str, timeout: float = 900):
    if where() != "dry" and not APPLY:
        print(f"$ {cmd.splitlines()[0]}   [not run — add --yes or SPARK_APPLY=1]")
        return None
    return sh(cmd, example=example, timeout=timeout)


REPO = "~/agenticaicodingfitness"
change('export HARDWARE_IP="$(hostname -I | awk \'{print $1}\')" && openshell provider create --name capstone-gateway '
       '--type openai --credential OPENAI_API_KEY="$(cat ~/w25/litellm/master.key)" '
       '--config OPENAI_BASE_URL="http://${HARDWARE_IP}:4000/v1"', example="✓ provider capstone-gateway created")
change("openshell inference set --provider capstone-gateway --model agent-brain && openshell inference get",
       example="provider: capstone-gateway\nmodel: agent-brain")
if where() == "dry" or APPLY:
    put(pol_path, "~/w25/capstone_policy.yaml")
change(f"openshell sandbox create --name {SB} --from base --policy ~/w25/capstone_policy.yaml "
       f"--upload {REPO}/week25/14_nat_agents:/sandbox/14_nat_agents --keep --no-tty -- true && "
       f"openshell sandbox upload {SB} {REPO}/week25/20_capstone_sovereign_agent /sandbox/capstone",
       example=f"✓ sandbox {SB} created · policy applied · phase: Ready")
change(f"openshell sandbox exec -n {SB} -- python3 -m venv /sandbox/.venv-nat && "
       f"openshell sandbox exec -n {SB} -- /sandbox/.venv-nat/bin/pip install -q 'nvidia-nat[langchain]~=1.9' greenlet && "
       f"openshell sandbox exec -n {SB} -- /sandbox/.venv-nat/bin/pip install -q --no-deps "
       f"-e /sandbox/14_nat_agents/hotel_ops_nat -e /sandbox/capstone/hotel_capstone_nat",
       example="Successfully installed … nvidia-nat-1.9.0 … hotel_ops_nat-0.1.0 hotel_capstone_nat-0.1.0")
change(f"openshell policy update {SB} --remove-rule pypi --wait", example="policy revision 2 loaded · groups: inference, gateway")
change(f"openshell sandbox exec -n {SB} --workdir /sandbox/capstone "
       f"--env CAPSTONE_BRAIN_URL=https://inference.local/v1 "
       f"--env CAPSTONE_GATEWAY=http://host.openshell.internal:4000/v1 "
       f"--env HOTEL_GATEWAY_KEY=\"$(cat ~/w25/litellm/master.key)\" "
       f"-- /sandbox/.venv-nat/bin/nat run --config_file configs/capstone_agent.yml "
       f"--input \"{C.SCENARIOS[0]['message']}\"",
       example="Workflow Result:\nI have opened an urgent ticket (MT-…) and alerted Security …")
change(f"openshell sandbox exec -n {SB} -- curl -s --max-time 5 https://example.com || echo 'blocked ✓'",
       example="curl: (56) CONNECT tunnel failed, response 403\nblocked ✓")
note("In the sandbox the agent's brain is inference.local (provider = the gateway's agent-brain alias) and the "
     "router tool calls the gateway directly at host.openshell.internal:4000 (course assumption: the playbooks "
     "show that name for the host's :8000; port 4000 is ours — check `openshell logs` the first time).")

step(4, "the capstone scorecard")
card = []
gate_files = sorted(C.H.RUNS.glob("predictions_finetune_*.jsonl"))
if gate_files:
    rows_ = C.H.read_predictions(gate_files[-1])
    m = C.H.summarize([C.H.score_item(r["predict"], r["label"], r.get("prompt", "")) for r in rows_])
    passed = all(ok for *_, ok in C.H.gate(m))
    card.append(["router ship gate (Module 13)", "✓" if passed else "✕", f"{gate_files[-1].name}: dept {m['department_acc']:.0%}, urgent {m['urgent_recall']:.0%}"])
else:
    card.append(["router ship gate (Module 13)", "—", "no fine-tune predictions yet (needs Module 09 on a Spark)"])
acc = C.RUNS / "acceptance_agent.json"
if acc.is_file():
    a = json.loads(acc.read_text())
    ok_n = sum(s["ok"] for s in a["scenarios"])
    src = "LAPTOP STAND-IN" if a.get("stand_in") else "Sparks"
    card.append(["agent scenarios (lab 20-3)", "✓" if ok_n == len(a["scenarios"]) else "✕",
                 f"{ok_n}/{len(a['scenarios'])} accepted · {src} · {a['ts']}  "
                 + " ".join(f"{s['id']}{'✓' if s['ok'] else '✕'}" for s in a["scenarios"])])
else:
    card.append(["agent scenarios (lab 20-3)", "—", "run lab 20-3 first"])
card.append(["sandbox policy valid + fence (this lab)", "✓" if (not errs and fence_ok) else "✕",
             f"{len(groups) - 1} runtime groups after setup · {len(ATTEMPTS)} attempts checked (policykit model)"])
card.append(["sandbox applied on Spark A (this lab, --yes)", "—" if where() == "dry" or not APPLY else "run",
             "DRY: not applied" if where() == "dry" else ("applied" if APPLY else "add --yes")])
table(card, ["gate", "", "evidence"])
done = all(r[1] == "✓" for r in card)
result("CAPSTONE COMPLETE on real Sparks." if done else
       "Not complete yet: every — needs a Spark, every ✕ names the module to revisit. That is the honest state of a "
       "stack built on a laptop: the wiring is proven, the fine-tune and the sandbox are waiting for their Sparks.")
